name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          ocker-compose up -d && output=$(docker run --network container:app appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/)
          echo ${output}
          if [ "$output" != "Hello from root" ]; then
            echo "No response from http://localhost:5000" 
            exit 1
          fi
        
#       - name: Install node
#         uses: actions/setup-node@v1
#         with:
#           node-version: 16.x

#       - name: Install dependencies
#         run: npm install

#       - name: Test
        
          
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
    
        
