name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          docker-compose up -d && output=$(curl --connect-timeout 300 -X POST http://localhost:4201/api/user -H 'Content-Type: application/json' -d '{"user":{"firstName":"user One","lastName":"user One","email":"user1@gmail.com"}}' 2>/dev/null) 
          echo ${output}
          if [ "$output" != "Hello from root" ]; then
            echo "No response from http://localhost:4201/api/users" 
            exit 1
          fi
        
#       - name: Install node
#         uses: actions/setup-node@v1
#         with:
#           node-version: 16.x

#       - name: Install dependencies
#         run: npm install

#       - name: Test
        
          
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
    
        
