name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          output=$(lsof -i:4201 | grep LISTEN) 
          echo 'first'
          n=${#output}
          echo ${output}
          echo ${n}
          echo 'Hello'
          if [ "$output" != "Hello from root" ]; then
            echo "No response from http://localhost:4201/api/users" 
            exit 1
          fi
        
#       - name: Install node
#         uses: actions/setup-node@v1
#         with:
#           node-version: 16.x

#       - name: Install dependencies
#         run: npm install

#       - name: Test
        
          
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
    
        
